// CART
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const QUANTITY_CHANGED = 'QUANTITY_CHANGED';
export const CLEAR_CART= 'CLEAR_CART';

// PRODUCTS
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';

//CONDITION
export const TOGGLE_ADD_MODAL = 'TOGGLE_ADD_MODAL';